theme: minima
author: "Ethan Lindahl                Email Address: Ethan.Lindahl4444@gmail.com"
title: Project Portfolio EML
description: "About Me: My name is Ethan Lindahl and Im looking to become a data analyst in the near future and this is my portfolio website. I am 22 years old, love video games and fishing, and am very much looking forward to what my future in coding and data analytics holds."
