theme: minima
author: Ethan Lindahl
title: Project Portfolio EML
description: About Me: My name is Ethan Lindahl and Im looking to become a data analyst in the near future and this is my portfolio website. I will post my future projects here and will keep updating this as my skills continue to improve.
